### ISSUE TITLE
Update downloads

### ISSUE THREAD

**Issue by owcz** [pepaslabs/pogoplug_mobile_uboot_installer#1]
Should the bodhi uboot be updated to [this 2016.05 version](http://forum.doozan.com/read.php?3,12381)?

Also the download.qnology.com has been offline for what feels like the last several months—probably time to default to your mirror

I'm also getting a different hash for http://ssl.pepas.com/pogo/uboot.sh:
`27fe40cf074bf1763bd8006407106b70  uboot.sh`
Has it been updated?

**Comment by radostyle** [comment]
I also had the issue with download.qnology.com being down.

**Comment by cellularmitosis** [comment]
Thanks for reporting this!

I've updated the script to point to the mirrored files rather than download.qnology.com (and updated the md5 sum mentioned in the README).

Unfortunately I don't have a pogoplug on-hand to test out the 2016.05 version (most of my stuff is in storage at the moment), so I'll delay on that one for now.

**Comment by cellularmitosis** [comment]
(note: I pulled the 2016.05 update request out into its own ticket so that I can close this one)

**Comment by owcz** [comment]
Just a heads up that bodhi mentioned a script in development for doing the install—not sure if it's ready yet but I know it's close and probably better than the qnology steps given how the project's progressed
